### PR TITLE
Added lua indent file 

### PR DESCRIPTION
**Pull request by ssteinbach**
Not sure if you're interested in this, but I added the indent file for lua as well.  Also not sure if I did it correctly, just copied the lua.vim file from the vim indent directory.

### CODE REVIEW

**Comment by justinj** [comment]
Oh sweet! I kept meaning to look into how to fix that, thanks! (sorry for taking a while, had a busy couple months)

**Comment by ssteinbach** [comment]
Cool!  I also added this to my `~/.vimrc`, is there a way to include this somewhere in the repo as well?

``` vim
" Pico8
au FileType pico8 setl sw=1 sts=1 et
au FileType pico8 setl commentstring=--%s
```

**Comment by justinj** [comment]
I was going to say I didn't want to change the `sw` and `sts` but the more I think about it the more I think you're right that it should be 1 like PICO-8 usually is. Yeah this seems like a great idea (I've also been meaning to fix the `commentstring` thing >_>)!

I think that should go in an `ftplugin` ([like here](https://github.com/xolox/vim-lua-ftplugin/blob/master/ftplugin/lua.vim)), if you wanted to add it?

**Comment by ssteinbach** [comment]
Sounds great, I'll do that quickly and open another PR.   Thanks!

**Pull request merged**
